steps:
  - name: 'golang'
    args: ['go','mod','init','github.com/golang/glog']
  - name: 'golang'
    args: ['go','list','-f','{{ .Dir }}','-m','github.com/golang/glog']
options:
  volumes:
    - name: go-modules
      path: /go